[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pylai"
version = "0.0.2"
description = "AI software engineering library"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name="Maxime BLIDI", email="blidi.maxime@gmail.com" }
]
dependencies = [
    "python-dotenv>=1.0.0",
    "tqdm",
    "pydantic",
    "pydantic-ai-slim[openai,mcp]"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
all = ["pylai[agentic,api]"]
# Agentic AI module (built on pydantic-ai)
agentic = [
    "pylai[graph,orchestrator,rag]",
]
graph = ["pylcloud @ https://github.com/PyYel/pylcloud/archive/refs/heads/main.tar.gz"]
orchestrator = []
rag = ["pylcloud[elasticsearch,opensearch] @ https://github.com/PyYel/pylcloud/archive/refs/heads/main.tar.gz"]
# API demo module
api = [
    "fastapi",
    "requests"
]


[tool.setuptools.packages.find]
where = ["."]
